### ISSUE TITLE
바 형태 말고 원형 그래프도 만들어주세요

### ISSUE THREAD

**Issue by ensuta** [ArpaAP/sir-sandbox#1]
바 형태 말고 원형 그래프도 만들어주세요
https://blog.logrocket.com/using-chart-js-react/

**Comment by ArpaAP** [comment]
해당 웹앱은 학교 프로젝트용으로써 목적을 다한 셈이라, 다른 프로젝트로 시간적 여유가 많지 않아 더 이상의 업데이트는 아마 진행하지 않을것 같습니다. 다만 PR은 적극적으로 환영하고 있습니다!
